"""added drone damage

Revision ID: 129cc7fa6552
Revises: af0da7523bda
Create Date: 2024-11-18 15:56:01.708943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129cc7fa6552'
down_revision = 'af0da7523bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_local_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cflt_drone_damage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_local_state', schema=None) as batch_op:
        batch_op.drop_column('cflt_drone_damage')

    # ### end Alembic commands ###
