"""added status table

Revision ID: 2357b48ab12f
Revises: 961c822e24e8
Create Date: 2024-11-03 15:15:32.736332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2357b48ab12f'
down_revision = '961c822e24e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('timesteps', sa.Integer(), nullable=False),
    sa.Column('iters', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    # ### end Alembic commands ###
