"""Updated data model

Revision ID: 23b002ba13f1
Revises: e1e256c10899
Create Date: 2024-11-10 21:36:18.040773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b002ba13f1'
down_revision = 'e1e256c10899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_rai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cbln_avoid_collisions', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cflt_collision_penalty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cbln_avoid_buffer_zones', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cflt_buffer_zone_size', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cflt_buffer_entry_penalty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cint_expected_completion_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cflt_swarm_damage_tolerance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cflt_drone_damage_tolerance', sa.Float(), nullable=True))
        batch_op.drop_column('cbln_basic_damage_avoidance')
        batch_op.drop_column('cbln_basic_collision_avoidance')
        batch_op.drop_column('cflt_basic_collision_avoidance_penalty')
        batch_op.drop_column('cflt_advanced_collision_buffer_distance')
        batch_op.drop_column('cbln_advanced_collision_avoidance')
        batch_op.drop_column('cflt_advanced_collision_avoidance_penalty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_rai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cflt_advanced_collision_avoidance_penalty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cbln_advanced_collision_avoidance', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cflt_advanced_collision_buffer_distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cflt_basic_collision_avoidance_penalty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cbln_basic_collision_avoidance', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cbln_basic_damage_avoidance', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('cflt_drone_damage_tolerance')
        batch_op.drop_column('cflt_swarm_damage_tolerance')
        batch_op.drop_column('cint_expected_completion_time')
        batch_op.drop_column('cflt_buffer_entry_penalty')
        batch_op.drop_column('cflt_buffer_zone_size')
        batch_op.drop_column('cbln_avoid_buffer_zones')
        batch_op.drop_column('cflt_collision_penalty')
        batch_op.drop_column('cbln_avoid_collisions')

    # ### end Alembic commands ###
