"""new reward data

Revision ID: 76a1016a05cf
Revises: dd154b72f69d
Create Date: 2024-11-30 19:11:21.183077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a1016a05cf'
down_revision = 'dd154b72f69d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cflt_target_distance_reward', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cint_all_collisions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cflt_drone_obstacle_distance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cflt_improvement_multiplier', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_rewards', schema=None) as batch_op:
        batch_op.drop_column('cflt_improvement_multiplier')
        batch_op.drop_column('cflt_drone_obstacle_distance')
        batch_op.drop_column('cint_all_collisions')
        batch_op.drop_column('cflt_target_distance_reward')

    # ### end Alembic commands ###
