"""expanded rewards

Revision ID: 938e3e541c8a
Revises: 27de0ab52f5c
Create Date: 2024-12-10 17:42:22.925832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938e3e541c8a'
down_revision = '27de0ab52f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cflt_collision_penalty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cflt_buffer_penalty', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_rewards', schema=None) as batch_op:
        batch_op.drop_column('cflt_buffer_penalty')
        batch_op.drop_column('cflt_collision_penalty')

    # ### end Alembic commands ###
