"""initial migration

Revision ID: 961c822e24e8
Revises: 
Create Date: 2024-11-03 15:12:51.951718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961c822e24e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_drone_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cflt_run_id', sa.Float(), nullable=True),
    sa.Column('cint_episode_id', sa.Integer(), nullable=True),
    sa.Column('cint_drone_id', sa.Integer(), nullable=True),
    sa.Column('cflt_linear_velocity', sa.Float(), nullable=False),
    sa.Column('cflt_angular_velocity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_global_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cflt_run_id', sa.Float(), nullable=True),
    sa.Column('cint_episode_id', sa.Integer(), nullable=True),
    sa.Column('cstr_state_encoding', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_local_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cflt_run_id', sa.Float(), nullable=True),
    sa.Column('cint_episode_id', sa.Integer(), nullable=True),
    sa.Column('cint_drone_id', sa.Integer(), nullable=True),
    sa.Column('cflt_x_coord', sa.Float(), nullable=False),
    sa.Column('cflt_y_coord', sa.Float(), nullable=False),
    sa.Column('cflt_orientation', sa.Float(), nullable=False),
    sa.Column('cflt_linear_velocity', sa.Float(), nullable=False),
    sa.Column('cflt_angular_velocity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_map_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cflt_run_id', sa.Float(), nullable=True),
    sa.Column('cflt_x_coord', sa.Float(), nullable=True),
    sa.Column('cflt_y_coord', sa.Float(), nullable=True),
    sa.Column('cstr_point_type', sa.String(), nullable=True),
    sa.Column('cint_obstacle_id', sa.Integer(), nullable=True),
    sa.Column('cstr_obstacle', sa.String(), nullable=True),
    sa.Column('cflt_obstacle_risk', sa.Float(), nullable=True),
    sa.Column('cstr_obstacle_color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_model_run_params',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cflt_run_id', sa.Float(), nullable=True),
    sa.Column('cstr_environment_id', sa.String(), nullable=False),
    sa.Column('cint_timesteps_per_batch', sa.Integer(), nullable=False),
    sa.Column('cflt_max_kl', sa.Float(), nullable=False),
    sa.Column('cint_cg_iters', sa.Integer(), nullable=False),
    sa.Column('cflt_cg_damping', sa.Float(), nullable=False),
    sa.Column('cflt_gamma', sa.Float(), nullable=False),
    sa.Column('cflt_lam', sa.Float(), nullable=False),
    sa.Column('cint_vf_iters', sa.Integer(), nullable=False),
    sa.Column('cint_vf_stepsize', sa.Integer(), nullable=False),
    sa.Column('cint_nr_agents', sa.Integer(), nullable=False),
    sa.Column('cstr_obs_mode', sa.String(), nullable=False),
    sa.Column('cint_comm_radius', sa.Integer(), nullable=False),
    sa.Column('cint_world_size', sa.Integer(), nullable=False),
    sa.Column('cint_distance_bins', sa.Integer(), nullable=False),
    sa.Column('cint_bearing_bins', sa.Integer(), nullable=False),
    sa.Column('cbln_torus', sa.Boolean(), nullable=False),
    sa.Column('cstr_dynamics', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_model_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cflt_run_id', sa.Float(), nullable=True),
    sa.Column('cdtm_run_date', sa.Date(), nullable=False),
    sa.Column('cbln_terminal_episode', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_rai',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cflt_run_id', sa.Float(), nullable=True),
    sa.Column('cbln_basic_collision_avoidance', sa.Boolean(), nullable=True),
    sa.Column('cflt_basic_collision_avoidance_penalty', sa.Float(), nullable=True),
    sa.Column('cbln_advanced_collision_avoidance', sa.Boolean(), nullable=True),
    sa.Column('cflt_advanced_collision_buffer_distance', sa.Float(), nullable=True),
    sa.Column('cflt_advanced_collision_avoidance_penalty', sa.Float(), nullable=True),
    sa.Column('cbln_basic_damage_avoidance', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_rewards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cflt_run_id', sa.Float(), nullable=True),
    sa.Column('cint_episode_id', sa.Integer(), nullable=True),
    sa.Column('cflt_reward', sa.Float(), nullable=False),
    sa.Column('cflt_pre_rai_reward', sa.Float(), nullable=True),
    sa.Column('cflt_rai_penalty', sa.Float(), nullable=True),
    sa.Column('cflt_rai_distance', sa.Float(), nullable=True),
    sa.Column('cflt_rai_incurred_risk', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_rewards')
    op.drop_table('tbl_rai')
    op.drop_table('tbl_model_runs')
    op.drop_table('tbl_model_run_params')
    op.drop_table('tbl_map_data')
    op.drop_table('tbl_local_state')
    op.drop_table('tbl_global_state')
    op.drop_table('tbl_drone_actions')
    # ### end Alembic commands ###
