"""added improvement multiplier

Revision ID: af0da7523bda
Revises: 23b002ba13f1
Create Date: 2024-11-17 05:16:16.770115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0da7523bda'
down_revision = '23b002ba13f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_local_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cflt_improvement_multiplier', sa.Float(), nullable=True))
        batch_op.alter_column('cflt_drone_obstacle_distance',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_local_state', schema=None) as batch_op:
        batch_op.alter_column('cflt_drone_obstacle_distance',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('cflt_improvement_multiplier')

    # ### end Alembic commands ###
