"""updated local_state

Revision ID: e1e256c10899
Revises: ea46f0bce7b1
Create Date: 2024-11-05 09:55:03.707730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e256c10899'
down_revision = 'ea46f0bce7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_local_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cint_drone_collisions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cflt_drone_obstacle_distance', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_local_state', schema=None) as batch_op:
        batch_op.drop_column('cflt_drone_obstacle_distance')
        batch_op.drop_column('cint_drone_collisions')

    # ### end Alembic commands ###
