"""Add description column to my_table

Revision ID: ea46f0bce7b1
Revises: 2357b48ab12f
Create Date: 2024-11-05 09:30:58.870240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea46f0bce7b1'
down_revision = '2357b48ab12f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cflt_distance_reward', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cflt_action_penalty', sa.Float(), nullable=True))
        batch_op.drop_column('cflt_rai_incurred_risk')
        batch_op.drop_column('cflt_rai_distance')
        batch_op.drop_column('cflt_rai_penalty')
        batch_op.drop_column('cflt_pre_rai_reward')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cflt_pre_rai_reward', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cflt_rai_penalty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cflt_rai_distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cflt_rai_incurred_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('cflt_action_penalty')
        batch_op.drop_column('cflt_distance_reward')

    # ### end Alembic commands ###
